### ISSUE TITLE
incsearch doesn't work in Vim 7.3 with vim-search-pulse plugin

### ISSUE THREAD

**Issue by jonthn** [haya14busa/incsearch.vim#61]
Whenever I press `/` nothing happens and this error appears in `:messages`

```
function incsearch#forward..<SNR>110_search..<SNR>110_get_input..154..152..165..138..188..<SNR>120_call..258..252..<SNR>144__auto_cmap..<SNR>
145_rhs_key_list, line 5 Vim(return):E118: Too many arguments for function: maparg
```

Below you will find a reduced/simplified version of my `.vimrc` that reproduce the problem

```
" vim:fdm=marker
"
" basically vi rest in peace
set nocompatible

scriptencoding utf-8

" set EDITORHOME to the root directory of the plug-ins and vim user files
let $EDITORHOME=get(split(&runtimepath, ','), 0)

" Utilities functions ----------------------------------------------------- {{{
function! CheckMake_dir(dir)
  if exists("*mkdir")
    if !isdirectory(a:dir)
      call mkdir(a:dir, 'p')
    endif
  endif
  return isdirectory(a:dir)
endfunction

" }}}

" Prefer POSIX shell
if &shell =~# 'fish$'
  set shell=/bin/sh
endif

let g:plug_window = "below new"

" Plugins Manager --------------------------------------------------------- {{{

if has('vim_starting')

  let s:plugins_manager_url = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  let s:plugins_manager_corefile = $EDITORHOME . '/' . 'autoload/plug.vim'

  " check the plug-ins manager is installed
  function! CheckPluginsManager()
    return !empty(glob(s:plugins_manager_corefile))
  endfunction

  " function to detect and install if it's not the case the plug-ins manager
  function! PluginsManagerOnDisk()
    if !CheckPluginsManager()
      if 1 == confirm("Install plugins manager ?", "&Yes\n&No", 2)
    if CheckMake_dir(fnamemodify(s:plugins_manager_corefile, ":p:h"))
      if executable('curl')
        execute '!curl -fLo '. s:plugins_manager_corefile . ' ' . s:plugins_manager_url
        if !v:shell_error
          if has("autocmd")
        autocmd VimEnter * PlugInstall
          endif
        endif
      elseif executable('wget')
        execute '!wget -O '. s:plugins_manager_corefile . ' ' . s:plugins_manager_url
        if !v:shell_error
          if has("autocmd")
        autocmd VimEnter * PlugInstall
          endif
        endif
      else
        echohl ErrorMsg | echomsg "curl or wget necessary" | echohl NONE
      endif
    else
      echohl ErrorMsg | echomsg "No plug-ins manager found!" | echohl NONE
    endif
      endif
    endif
  endfunction

  call PluginsManagerOnDisk()

endif

try
  call plug#begin()

  Plug 'haya14busa/incsearch.vim'
  Plug 'inside/vim-search-pulse'

  call plug#end()

  let g:vim_search_pulse_disable_auto_mappings = 1
  map /  <Plug>(incsearch-forward)
  map ?  <Plug>(incsearch-backward)
  map g/ <Plug>(incsearch-stay)

catch
  let s:plugins_manager_active = 0
finally
endtry

```
# To reproduce

```
$ vim
```

Which will ask to download and install vim-plug, at first launch it will install missing plugins afterwards to you can quit vim

```
$ vim ~/.vimrc 
```

Then search for 'nocomp' as an example.
Nothing will happen and when you type `:messages` you will see the error

```
$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep  9 2014 16:30:51)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

**Comment by haya14busa** [comment]
Thanks for the report @jonthn 

I guess this has nothing to do with vim-search-pulse. The problem is the vim version.
Since Vim v7-3-032, the number of arguments for `maparg()` change from 3 to 4.

I'll fix it but I suggest you updating Vim:)

**Comment by jonthn** [comment]
Thanks for the feedback.
It's one of the first thing I do on a new machine but in that case it's the "stock" version of Vim provided on OSX so that's why I encountered this issue before I installed a newer version.

**Comment by haya14busa** [comment]
> I'll fix it

Hmm.... from a quick read, it's really hard to handle it for old Vim, so incsearch.vim probably require Vim version over 7.3.032.

**Comment by jonthn** [comment]
That's fine by me, I think in that case it would be best to show an error message and/or deactivate incsearch completely when the Vim version is too old.

Thanks for your help and support

**Comment by haya14busa** [comment]
I'll close this issue.

As for the error message, I think I can ignore Vim 7.3 these days.
